import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect } from 'react'
import styles from 'assets/styles/Home.module.css'
import { testAction } from 'redux/store/actions'
import { connect } from 'react-redux'
import { Button } from 'rsuite'

function Home(props) {
  useEffect(() => {
    console.log(props)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>
      </main>
      <button type="button" onClick={props.testAction} className="tw-bg-green-500  bg-green-500">
        Buttonscscc
      </button>
      <Button appearance="primary" href="https://rsuitejs.com/">
        Getting started
      </Button>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
const mapStateToProps = state => {
  return {}
}
const mapDispatchToProps = { testAction }
export default connect(mapStateToProps, mapDispatchToProps)(Home)
